### PR TITLE
Created hello in Java.

### PR DESCRIPTION
**Pull request by hatsh3p**
#1

### CODE REVIEW

**Review by tubingtime — CHANGES_REQUESTED** [review]
Great code but needs more exclamation points.

**Review by tubingtime — APPROVED** [review]
AMAZING!!!!!!!!!!!!!!!!!!!!!!!!!11111

**Comment by hatsh3p** [comment]
Created hello world in Java and got approved.

**Comment by hatsh3p** [comment]
Oops

**Pull request merged**
